## 6/23/26 pandas

### 创建Series

In [1]:
import pandas as pd
# 使用列表创建
s = pd.Series([10, 2, 3,  4, 5])
print(s)

# 自定义索引与name
s = pd.Series([10, 2, 3, 4, 5], index = [6, 'a', 8, 9, 100], name = '名字')
print(s)

0    10
1     2
2     3
3     4
4     5
dtype: int64
6      10
a       2
8       3
9       4
100     5
Name: 名字, dtype: int64

In [2]:
# 使用字典来创建
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}, name = 'name111')
print(s)

# 从原序列按照index获取对应组合创建新series
s1 = pd.Series(s, index = ['a', 'c'])
print(s1)

a    1
b    2
c    3
d    4
e    5
Name: name111, dtype: int64
a    1
c    3
Name: name111, dtype: int64

### 属性

In [3]:
# 索引与值
print(s.index, s.values)

# 形状, 维数, 元素个数, 元素类型
print(s.shape, s.ndim, s.size, s.dtype)

# 名字
print(s.name)

# 显式索引(标签)及切片, 隐式索引(下标), 单个元素访问(不可切片)
print(s.loc['a'], '\n', s.loc['a': 'c'], s.iloc[0])
print(s.at['a'], s.iat[0])

# 不建议在该库下使用python原生索引方式, 防止显式与隐式冲突

Index(['a', 'b', 'c', 'd', 'e'], dtype='str') [1 2 3 4 5]
(5,) 1 5 int64
name111
1
 a    1
b    2
c    3
Name: name111, dtype: int64 1
1 1

In [4]:
# 返回series前五行的内容
print(s.head())
# 返回series后五行的内容
print(s.tail())
# 可传入参数, 返回设定的行数, 默认为5
# 用于快捷查看元素内容

a    1
b    2
c    3
d    4
e    5
Name: name111, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: name111, dtype: int64

### 常见函数

In [5]:
import numpy as np
# pandas会将np的缺失值及原生的None全记作NaN
s = pd.Series([10, 2, np.nan, None, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e', 'f', 'g'], name = 'Data')

s.head(3).to_frame()    # 不打印, 直接获取表格形式, 并渲染

   Data
a  10.0
b   2.0
c   NaN

In [6]:
# 查看所有描述性信息
s.describe().to_frame()
# 几种统计方法的值都在这里, 写法与np一样, 注意计算时排除缺失值

            Data
count   5.000000
mean    4.800000
std     3.114482
min     2.000000
25%     3.000000
50%     4.000000
75%     5.000000
max    10.000000

In [7]:
# 获取元素个数(忽略缺失值)
print(s.count())

# 两种获取索引的方法
print(s.keys())
print(s.index)

# 判断每一个元素是否为缺失值
s.isna().to_frame()

# 检查series的每个元素是否在给定集合中
s.isin([4, 5, 6]).to_frame()

5
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

    Data
a  False
b  False
c  False
d  False
e  False
f   True
g   True

In [8]:
# 分位数写法与np有区别
s.quantile(0.25)

np.float64(3.0)

In [9]:
# 众数, 按照出现频率计算
print(s.mode())

# 列表元素计数
print(s.value_counts())

# 按值与按索引排序
print(s.sort_values())
print(s.sort_index())

0     2.0
1     3.0
2     4.0
3     5.0
4    10.0
Name: Data, dtype: float64
Data
10.0    1
2.0     1
3.0     1
4.0     1
5.0     1
Name: count, dtype: int64
b     2.0
e     3.0
f     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: Data, dtype: float64
a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
Name: Data, dtype: float64

In [10]:
# 去重
print(s.drop_duplicates())
# 这里对缺失值进行了去重

# 去重后的元素与个数
print(s.nunique())

a    10.0
b     2.0
c     NaN
e     3.0
f     4.0
g     5.0
Name: Data, dtype: float64
5

### 6/25/26 series案例

1 学生成绩统计\
创建包含10名学生的Series, 成绩范围在50-100之间\
计算平均分 最高分 最低分 找出高于平均分的人数

In [11]:
np.random.seed(42)
scores = pd.Series(np.random.randint(50, 101, 10), index = ['学生'+str(i) for i in range(1, 11)])

print(scores)
print(scores.mean())
print(scores.max())
print(scores.min())
mean = scores.mean()
print(len(scores[scores > mean]))    # 布尔索引筛选, 或使用.count()代替len计数

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int32
73.7
92
57
4

2 温度数据分析\
给定某城市一周内每天最高温度series\
找出温度超过30的天数\
计算平均温度 将温度从高到低排序\
找出温度变化最大的两天

In [12]:
tem = pd.Series([28, 31, 29, 32, 30, 27, 33], index = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'])

print(tem[tem > 30].count())
print(tem.mean())
print(tem.sort_values(ascending = False))    # 是否升序排列

t = tem.diff().abs()    # 获取后一个元素与前一个元素的差值
date = t.sort_values(ascending = False).keys()
print(date)
print(*date[:2])   # 这和前边显式隐式索引不一样, 这里已经选取了key()列

3
30.0
周日    33
周四    32
周二    31
周五    30
周三    29
周一    28
周六    27
dtype: int64
Index(['周日', '周二', '周六', '周四', '周三', '周五', '周一'], dtype='str')
周日 周二

3 股票价格分析\
给定10天收盘价\
计算每日收益率, 当日 / 前日 - 1\
找出收益率最高和最低的日期\
计算波动率(标准差)

In [13]:
prices = pd.Series([102.3, 103.5, 105.1, 104.8, 106.2, 107.0, 106.5, 108.1, 109.3, 110.2], \
                   index = pd.date_range('2023-01-01', periods = 10))    # 日期序列的函数
print(prices)
pct = prices.pct_change()    # 收益率的内置函数
print(pct)
print(pct.max(), pct.min())
print(pct.idxmax(), pct.idxmin())
print(pct.std())

2023-01-01    102.3
2023-01-02    103.5
2023-01-03    105.1
2023-01-04    104.8
2023-01-05    106.2
2023-01-06    107.0
2023-01-07    106.5
2023-01-08    108.1
2023-01-09    109.3
2023-01-10    110.2
Freq: D, dtype: float64
2023-01-01         NaN
2023-01-02    0.011730
2023-01-03    0.015459
2023-01-04   -0.002854
2023-01-05    0.013359
2023-01-06    0.007533
2023-01-07   -0.004673
2023-01-08    0.015023
2023-01-09    0.011101
2023-01-10    0.008234
Freq: D, dtype: float64
0.015458937198067568 -0.004672897196261627
2023-01-03 00:00:00 2023-01-07 00:00:00
0.007373623845361105

4 销售数据分析\
计算季度平均销量, 找出销量最高月份\
计算月环比增长率\
找出连续增长超过两个月的月份\
同比增长指本月与去年本月相比, 环比指本月与上月相比

In [14]:
sales = pd.Series([120, 135, 145, 160, 155, 170, 180, 175, 190, 200, 210, 220], \
                   index = pd.date_range('2022-01-01', periods = 12, freq = "MS"))  # 按月初生成
print(sales)
season = sales.resample("QS")    # 按季度重新采样
print(season.mean())
print(sales.idxmax())

pct = sales.pct_change(); print(pct)
pct_bool = pct > 0
pct_bool.rolling(3).sum()                                          # 宽度为3的滑动窗口求和
print(len(pct_bool[pct_bool.rolling(3).sum() > 2]))                # 布尔索引并计数
print(*pct_bool[pct_bool.rolling(3).sum() > 2].keys().tolist())    # 打印这些满足条件的标签

2022-01-01    120
2022-02-01    135
2022-03-01    145
2022-04-01    160
2022-05-01    155
2022-06-01    170
2022-07-01    180
2022-08-01    175
2022-09-01    190
2022-10-01    200
2022-11-01    210
2022-12-01    220
Freq: MS, dtype: int64
2022-01-01    133.333333
2022-04-01    161.666667
2022-07-01    181.666667
2022-10-01    210.000000
Freq: QS-JAN, dtype: float64
2022-12-01 00:00:00
2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64
3
2022-04-01 00:00:00 2022-11-01 00:00:00 2022-12-01 00:00:00

5 每小时销售数据分析\
按天重采样计算每日总销售额\
计算每天营业时间(8-22点)和非营业时间的销售额比例\
找出销售额最高的三个小时

In [15]:
np.random.seed(42)
hourly_sales = pd.Series(np.random.randint(0, 100, 24), \
                         index = pd.date_range('2025-01-01', periods = 24, freq = 'h'))

total = hourly_sales.resample('D').sum()      # 按天重采样的总销售额
hourly_sales.between_time('8:00', '22:00')    # 筛选一段时间内Series
business = hourly_sales[(hourly_sales.index.hour <= 22) & (hourly_sales.index.hour >= 8)]    # 或采用布尔索引方式
# hourly_sales.drop(business) # 可以使用drop去掉营业时间的数据
print(business.sum() / (total - business.sum()))

print(hourly_sales.nlargest(3))    # 取出最大的几个数据, 或sort_values(ascending=False)

2025-01-01    1.429435
Freq: D, dtype: float64
2025-01-01 11:00:00    99
2025-01-01 01:00:00    92
2025-01-01 10:00:00    87
dtype: int32

### 6/27/26 创建Dataframe
区别于Series, Dataframe为二维数据表, 可以看作多个Series拼接在一起

In [16]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])
df = pd.DataFrame({"c1": s1, "c2": s2})    # 需使用字典创建dataframe, 或者展开如下
df1 = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],\
        "name": ['a', 'b', 'c', 'd', 'e'],\
        "age": [12, 14, 13, 11, 15],\
        "score": [60.5, 72, 65, 76, 76.5]
    }, index = ['r1', 'r2', 'r3', 'r4', 'r5'], columns = ["score", "id", "name", "age"]
    # 指定行索引与列顺序
)
df1

    score  id name  age
r1   60.5   1    a   12
r2   72.0   2    b   14
r3   65.0   3    c   13
r4   76.0   4    d   11
r5   76.5   5    e   15

### 属性
与series相比增加了columns, 上文应用过了

In [17]:
# 行索引
print(df1.index)
# 列标签
print(df1.columns)
# 值
print(df1.values)
# 维度
print(df1.ndim)
# 数据类型
print(df1.dtypes)
# 形状
print(df1.shape)
# 元素个数
print(df1.size)
# 转置
print(df1.T)
# 此时它的行索引与列标签相对调
print(df1.T.index)

Index(['r1', 'r2', 'r3', 'r4', 'r5'], dtype='str')
Index(['score', 'id', 'name', 'age'], dtype='str')
[[60.5 1 'a' 12]
 [72.0 2 'b' 14]
 [65.0 3 'c' 13]
 [76.0 4 'd' 11]
 [76.5 5 'e' 15]]
2
score    float64
id         int64
name         str
age        int64
dtype: object
(5, 4)
20
         r1    r2    r3    r4    r5
score  60.5  72.0  65.0  76.0  76.5
id        1     2     3     4     5
name      a     b     c     d     e
age      12    14    13    11    15
Index(['score', 'id', 'name', 'age'], dtype='str')

In [18]:
print(df1)
# 获取某行数据
print(df1.loc['r1'])
print(df1.iloc[0])
# 获取某位置数据
print(df1.at['r2', 'score'])
print(df1.iat[1, 0])

    score  id name  age
r1   60.5   1    a   12
r2   72.0   2    b   14
r3   65.0   3    c   13
r4   76.0   4    d   11
r5   76.5   5    e   15
score    60.5
id          1
name        a
age        12
Name: r1, dtype: object
score    60.5
id          1
name        a
age        12
Name: r1, dtype: object
72.0
72.0

In [19]:
# 获取多列数据
print(df1['score'])    # 直接写入列名或行名, 套两层会返回一个Dataframe
print(df1.score)       # 这两者的效果是相同的
print(df1[['score', 'id']])    # 获取了多列数据

# 获取多行数据
print(df1.head(2))
print(df1.tail(1))

r1    60.5
r2    72.0
r3    65.0
r4    76.0
r5    76.5
Name: score, dtype: float64
r1    60.5
r2    72.0
r3    65.0
r4    76.0
r5    76.5
Name: score, dtype: float64
    score  id
r1   60.5   1
r2   72.0   2
r3   65.0   3
r4   76.0   4
r5   76.5   5
    score  id name  age
r1   60.5   1    a   12
r2   72.0   2    b   14
    score  id name  age
r5   76.5   5    e   15

In [20]:
# 切片
df1[df1.score > 70]
df1[ (df1['score'] > 70) & (df1['id'] > 3)]

# 随机抽样
df1.sample(1)

    score  id name  age
r5   76.5   5    e   15

### 6/29/26 Dataframe案例

案例1 学生成绩分析\
计算每个学生成绩总分和平均分\
找出数学高于90或英语高于85的\
按总分从高到低排序

In [21]:
data = {
    '姓名': ['a', 'b', 'c', 'd', 'e'], \
    '数学': [85, 92, 78, 88, 95], \
    '英语': [90, 88, 85, 92, 80], \
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
print(scores)

scores['总分'] = scores[['数学', '英语', '物理']].sum(axis = 1)
print(scores)
scores['平均分'] = scores['总分'] / 3
print(scores)
scores['平均分'] = scores[['数学', '英语', '物理']].mean(axis = 1)    # 得到相同效果
print(scores)

  姓名  数学  英语  物理
0  a  85  90  75
1  b  92  88  80
2  c  78  85  88
3  d  88  92  85
4  e  95  80  90
  姓名  数学  英语  物理   总分
0  a  85  90  75  250
1  b  92  88  80  260
2  c  78  85  88  251
3  d  88  92  85  265
4  e  95  80  90  265
  姓名  数学  英语  物理   总分        平均分
0  a  85  90  75  250  83.333333
1  b  92  88  80  260  86.666667
2  c  78  85  88  251  83.666667
3  d  88  92  85  265  88.333333
4  e  95  80  90  265  88.333333
  姓名  数学  英语  物理   总分        平均分
0  a  85  90  75  250  83.333333
1  b  92  88  80  260  86.666667
2  c  78  85  88  251  83.666667
3  d  88  92  85  265  88.333333
4  e  95  80  90  265  88.333333

In [22]:
scores[ (scores['数学'] > 90) | (scores['英语'] > 85) ]

  姓名  数学  英语  物理   总分        平均分
0  a  85  90  75  250  83.333333
1  b  92  88  80  260  86.666667
3  d  88  92  85  265  88.333333
4  e  95  80  90  265  88.333333

In [23]:
scores.sort_values('总分', ascending = False).head(3)

  姓名  数学  英语  物理   总分        平均分
4  e  95  80  90  265  88.333333
3  d  88  92  85  265  88.333333
1  b  92  88  80  260  86.666667

案例2 销售数据分析\
计算销售额\
找出销售额最高的产品\
按销售额从高到低排序并输出产品信息

In [24]:
data = {
    '产品名称': ['a', 'b', 'c', 'd'], \
    '单价': [100, 150, 200, 120], \
    '销量': [50, 30, 20, 40]
}
df = pd.DataFrame(data)
df['总销售额'] = df['单价'] * df['销量']
df.nlargest(1, columns = ['总销售额'])
df.sort_values('总销售额', ascending = False)

  产品名称   单价  销量  总销售额
0    a  100  50  5000
3    d  120  40  4800
1    b  150  30  4500
2    c  200  20  4000

案例3 用户行为分析\
计算每位用户总消费金额\
找出消费金额最高的用户, 输出其全部信息\
计算所有用户平均消费金额,两位小数\
统计电子产品总购买量

In [25]:
data = {
    'id': [101, 102, 103, 104, 105], \
    '用户名': ['apple', 'butter', 'charlie', 'duff', 'edward'], \
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'], \
    '商品单价': [1200, 300, 800, 150, 200], \
    '购买数量': [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
df['总消费金额'] = df['商品单价'] * df['购买数量']
df.nlargest(1, columns = '总消费金额')
df['总消费金额'].mean()
df[df['商品类别'] == '电子产品']['购买数量'].sum()

np.int64(3)